# Generated by Django 4.1.7 on 2023-07-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_avilable_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.CharField(max_length=30)),
                ('csv', models.FileField(upload_to='upload_csv/%Y/%m/%d')),
            ],
        ),
    ]
