# Generated by Django 4.1.7 on 2023-07-24 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('[\'"+-=]', inverse_match=True, message='Avoid quotation and math operators')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[\'"+-=]', inverse_match=True, message='Avoid quotation and math operators')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[\'"+-=]', inverse_match=True, message='Avoid quotation and math operators')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[\'"+-=]', inverse_match=True, message='Avoid quotation and math operators')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[\'"+-=]', inverse_match=True, message='Avoid quotation and math operators')]),
        ),
    ]
